version: '3'

services:
  rasa:
    image: rasa/rasa:3.4.0a3
    command: run
    ports:
      - 5005:5005
    volumes:
      - ./app:/app
      - ./rasa_audiocodes:/opt/venv/lib/python3.10/site-packages/rasa_audiocodes

  actions:
    image: rasa/rasa:3.4.0a3
    command: run actions
    volumes:
      - ./app:/app
